"""initial schema

Creates the full Octagon Log schema and seeds the five baseline
shop areas (Sculpture, Ceramics, Metal Smithing, DigiLab, Woodworking).

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-04-10
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


SHOP_AREAS = ["Sculpture", "Ceramics", "Metal Smithing", "DigiLab", "Woodworking"]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_primary_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('shop_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('enrollment_term', sa.String(length=32), nullable=True),
    sa.Column('canvas_user_id', sa.String(length=32), nullable=True),
    sa.Column('care_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_canvas_user_id'), ['canvas_user_id'], unique=False)

    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('requires_training', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['shop_area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitor_areas',
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['shop_area.id'], ),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitor.id'], ),
    sa.PrimaryKeyConstraint('monitor_id', 'area_id')
    )
    op.create_table('monitor_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('signed_in_at', sa.DateTime(), nullable=True),
    sa.Column('signed_out_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['shop_area.id'], ),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('acknowledged_by_id', sa.Integer(), nullable=False),
    sa.Column('signed_in_at', sa.DateTime(), nullable=True),
    sa.Column('signed_out_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('signed_out_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['monitor.id'], ),
    sa.ForeignKeyConstraint(['area_id'], ['shop_area.id'], ),
    sa.ForeignKeyConstraint(['signed_out_by_id'], ['monitor.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('issued_by_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['shop_area.id'], ),
    sa.ForeignKeyConstraint(['issued_by_id'], ['monitor.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['monitor.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_training',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('certified_date', sa.DateTime(), nullable=True),
    sa.Column('certified_semester', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'equipment_id')
    )
    # ### end Alembic commands ###

    # Seed the five baseline shop areas. These are treated as fixed enum
    # values throughout the app, so they belong in the initial migration
    # rather than seed.py.
    shop_area_table = sa.table(
        "shop_area",
        sa.column("name", sa.String),
    )
    op.bulk_insert(
        shop_area_table,
        [{"name": name} for name in SHOP_AREAS],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_training')
    op.drop_table('warning')
    op.drop_table('student_visit')
    op.drop_table('monitor_session')
    op.drop_table('monitor_areas')
    op.drop_table('equipment')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_canvas_user_id'))

    op.drop_table('student')
    op.drop_table('shop_area')
    op.drop_table('monitor')
    op.drop_table('faculty')
    # ### end Alembic commands ###
